### ISSUE TITLE
Fail to build using treesitter version 0.21.* and newer

### ISSUE THREAD

**Issue by alisoleimani** [Z572/guile-ts#3]
Hello,

Recent versions of tree sitter do not export parser.h anymore so tests/tree-sitter-json.c can not be compiled, is it possible to revert this https://github.com/Z572/guile-ts/commit/f050c3e160ac40b9a48df1c1b44cbb6418e0965a?

**Comment by alisoleimani** [comment]
After taking a deeper look, it might need more than just this commit :(

**Comment by alisoleimani** [comment]
Thanks for the quick fix, I am trying to upgrade neovim in guix and needed to upgrade tree sitter first. when can you release a new tag to unblock upgrading to new tree sitter versions?

**Comment by Z572** [comment]
It's released now.
